version: "3.8"
services:
  # backend api built with golang
  backend:
    build: ./backend
    container_name: shortener_management_api
    env_file:
      - ./backend/.env
    ports:
      - 9090:9090
    depends_on:
      mongodb:
        condition: service_healthy
    links:
      - mongodb
    volumes:
      - ./backend/config.yaml:/app/config.yaml
      - ./backend/private.pem:/app/private.pem

  # mongodb is our primary data store
  mongodb:
    image: mongo:4.4.1-bionic
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/admin --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    command: mongod

  # nginx is used for ssl termination
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/nginx/conf.d/cert.pem:ro
      - ./nginx/key.pem:/etc/nginx/conf.d/key.pem:ro
    depends_on:
      - frontend
      - backend

  # frontend
  frontend:
    image: nginx:1.19.3-alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "3000:3000"
