version: "3.9"

services:
  backend:
    build: ./backend
    container_name: shortener_management_api
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    depends_on:
      otel-collector:
        condition: service_started
      mongodb:
        condition: service_started
    links:
      - mongodb
    volumes:
      - ./backend/config.yaml:/app/config.yaml
      - ./backend/private.pem:/app/private.pem

  mongodb:
    image: mongo:6.0.4-focal
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    command: mongod

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/nginx/conf.d/cert.pem:ro
      - ./nginx/key.pem:/etc/nginx/conf.d/key.pem:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: nginx:1.23.2-alpine
    container_name: nginx_frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "3000:3000"

  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.42.0
    ports:
      - "16686:16686"
      - "14250"
    environment:
      - LOG_LEVEL=debug

  zipkin-all-in-one:
    container_name: zipkin
    image: openzipkin/zipkin:2.24
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.42.0
    volumes:
      - ./telemetry/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      [
        "--path.procfs=/host/proc",
        "--path.rootfs=/rootfs",
        "--path.sysfs=/host/sys",
        "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
      ]
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    ports:
      - "8080:8080"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.71.0
    container_name: otel-collector
    command:
      [
        "--config=/etc/otel-collector-config.yaml",
        "${OTELCOL_ARGS}"
      ]
    volumes:
      - ./telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1777:1777" # pprof extension
      - "8887:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317" # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
    environment:
      - JAEGER_REPORTER_LOG_SPANS=true
