# Server configurations
server:
  address: ":9000"
  timeout: 20
  otlp_address: "otel-collector:55680"

  # Auth parameters
auth:
  key_id: "1"
  private_key_file: "./private.pem"
  algorithm: "RS256"

# MongoDB credentials
mongo:
  name: "shortener"
  user: "admin"
  pwd: "password"
  host_port: "mongodb:27017"
