name: Go backend test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Lint
        run: |
          cd backend
          make lint-prepare
          make lint
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        
      - name: Run Unit tests.
        run: |
          cd backend
          make test-coverage
        
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./backend/coverage.txt
